# To run this test, type the following commands in a terminal, inside this directory: 
# 1. make clean
# 2. make
# Now open two terminals, using split option
# 1. On the left: ./tcp_server
# 2. On the right: ./tcp_client

server:
	gcc -o tcp_server tcp_server.c
	gcc -o tcp_client TCPclient.c 

clean:
	rm -f tcp_server
	rm -f tcp_client